//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeSystem.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeSystem.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;e&quot;: &quot;trade&quot;,
        ///                &quot;s&quot;: &quot;BTCUSDT&quot;,
        ///                &quot;q&quot;: &quot;0.001&quot;,
        ///                &quot;T&quot;: 1678901234567
        ///            }.
        /// </summary>
        internal static string BinanceMissingPriceField {
            get {
                return ResourceManager.GetString("BinanceMissingPriceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;e&quot;: &quot;24hrTicker&quot;,
        ///                &quot;E&quot;: 1678901234567,
        ///                &quot;s&quot;: &quot;BTCUSDT&quot;,
        ///                &quot;p&quot;: &quot;50000.12&quot;,
        ///                &quot;q&quot;: &quot;0.001&quot;,
        ///                &quot;T&quot;: 1678901234567
        ///            }.
        /// </summary>
        internal static string BinanceNotTrade {
            get {
                return ResourceManager.GetString("BinanceNotTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;e&quot;: &quot;trade&quot;,
        ///                &quot;E&quot;: 1678901234567,
        ///                &quot;s&quot;: &quot;BTCUSDT&quot;,
        ///                &quot;t&quot;: 12345,
        ///                &quot;p&quot;: &quot;50000.12&quot;,
        ///                &quot;q&quot;: &quot;0.001&quot;,
        ///                &quot;b&quot;: 123456,
        ///                &quot;a&quot;: 123457,
        ///                &quot;T&quot;: 1678901234567,
        ///                &quot;m&quot;: false,
        ///                &quot;M&quot;: true
        ///            }.
        /// </summary>
        internal static string BinanceValidTrade {
            get {
                return ResourceManager.GetString("BinanceValidTrade", resourceCulture);
            }
        }
    }
}
